# Generated by Django 5.1.4 on 2024-12-13 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap6', '0002_studentprofile_achievements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='portfolio_url',
        ),
    ]
